/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardStatisticsRouteImport } from './routes/_dashboard/statistics'
import { Route as DashboardConfigsRouteImport } from './routes/_dashboard/configs'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardPredictionsIndexRouteImport } from './routes/_dashboard/predictions/index'
import { Route as DashboardPredictionsNewRouteImport } from './routes/_dashboard/predictions/new'
import { Route as DashboardPredictionsIdEditRouteImport } from './routes/_dashboard/predictions/$id.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStatisticsRoute = DashboardStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfigsRoute = DashboardConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPredictionsIndexRoute =
  DashboardPredictionsIndexRouteImport.update({
    id: '/predictions/',
    path: '/predictions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPredictionsNewRoute = DashboardPredictionsNewRouteImport.update({
  id: '/predictions/new',
  path: '/predictions/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPredictionsIdEditRoute =
  DashboardPredictionsIdEditRouteImport.update({
    id: '/predictions/$id/edit',
    path: '/predictions/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/configs': typeof DashboardConfigsRoute
  '/statistics': typeof DashboardStatisticsRoute
  '/users': typeof DashboardUsersRoute
  '/predictions/new': typeof DashboardPredictionsNewRoute
  '/predictions/': typeof DashboardPredictionsIndexRoute
  '/predictions/$id/edit': typeof DashboardPredictionsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/configs': typeof DashboardConfigsRoute
  '/statistics': typeof DashboardStatisticsRoute
  '/users': typeof DashboardUsersRoute
  '/': typeof DashboardIndexRoute
  '/predictions/new': typeof DashboardPredictionsNewRoute
  '/predictions': typeof DashboardPredictionsIndexRoute
  '/predictions/$id/edit': typeof DashboardPredictionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/configs': typeof DashboardConfigsRoute
  '/_dashboard/statistics': typeof DashboardStatisticsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/predictions/new': typeof DashboardPredictionsNewRoute
  '/_dashboard/predictions/': typeof DashboardPredictionsIndexRoute
  '/_dashboard/predictions/$id/edit': typeof DashboardPredictionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configs'
    | '/statistics'
    | '/users'
    | '/predictions/new'
    | '/predictions/'
    | '/predictions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configs'
    | '/statistics'
    | '/users'
    | '/'
    | '/predictions/new'
    | '/predictions'
    | '/predictions/$id/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/configs'
    | '/_dashboard/statistics'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/predictions/new'
    | '/_dashboard/predictions/'
    | '/_dashboard/predictions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/statistics': {
      id: '/_dashboard/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof DashboardStatisticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/configs': {
      id: '/_dashboard/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof DashboardConfigsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/predictions/': {
      id: '/_dashboard/predictions/'
      path: '/predictions'
      fullPath: '/predictions/'
      preLoaderRoute: typeof DashboardPredictionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/predictions/new': {
      id: '/_dashboard/predictions/new'
      path: '/predictions/new'
      fullPath: '/predictions/new'
      preLoaderRoute: typeof DashboardPredictionsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/predictions/$id/edit': {
      id: '/_dashboard/predictions/$id/edit'
      path: '/predictions/$id/edit'
      fullPath: '/predictions/$id/edit'
      preLoaderRoute: typeof DashboardPredictionsIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConfigsRoute: typeof DashboardConfigsRoute
  DashboardStatisticsRoute: typeof DashboardStatisticsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPredictionsNewRoute: typeof DashboardPredictionsNewRoute
  DashboardPredictionsIndexRoute: typeof DashboardPredictionsIndexRoute
  DashboardPredictionsIdEditRoute: typeof DashboardPredictionsIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConfigsRoute: DashboardConfigsRoute,
  DashboardStatisticsRoute: DashboardStatisticsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPredictionsNewRoute: DashboardPredictionsNewRoute,
  DashboardPredictionsIndexRoute: DashboardPredictionsIndexRoute,
  DashboardPredictionsIdEditRoute: DashboardPredictionsIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
