
// gemini_service_v1.js
// Handles communication with the Gemini API.

export async function callGemini(prompt, apiKey) {
    if (!apiKey) {
        throw new Error("API Key is missing. Please provide a valid Gemini API Key.");
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const payload = {
        contents: [{
            parts: [{ text: prompt }]
        }],
        generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 16384,
        }
    };

    try {
        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`Gemini API Error: ${response.status} - ${JSON.stringify(errorData)}`);
        }

        const data = await response.json();

        // Extract text from response
        if (data.candidates && data.candidates.length > 0) {
            return data.candidates[0].content.parts[0].text;
        } else {
            return "No content generated by Gemini.";
        }

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw error;
    }
}
