
// openai_service_v1.js
// Handles communication with the OpenAI API (backup for Gemini).

export async function callOpenAI(prompt, apiKey) {
    if (!apiKey) {
        throw new Error("API Key is missing. Please provide a valid OpenAI API Key.");
    }

    const url = "https://api.openai.com/v1/chat/completions";

    const payload = {
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.3,
        max_tokens: 16384,
    };

    try {
        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${apiKey}`,
            },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`OpenAI API Error: ${response.status} - ${JSON.stringify(errorData)}`);
        }

        const data = await response.json();

        // Extract text from response
        if (data.choices && data.choices.length > 0) {
            return data.choices[0].message.content;
        } else {
            return "No content generated by OpenAI.";
        }

    } catch (error) {
        console.error("Error calling OpenAI API:", error);
        throw error;
    }
}
