import * as Joi from 'joi';
require('dotenv').config();

export const envSchema: Joi.ObjectSchema = Joi.object({
  APP_HOST: Joi.string().required(),
  APP_PORT: Joi.number().required(),
  APP_ENV: Joi.string().required(),
  APP_URL: Joi.string().optional(),
  ALLOWED_ORIGINS: Joi.string().optional(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_EXPIRY: Joi.string().optional(),
  TZ: Joi.string().optional(),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  APPLE_CLIENT_ID: Joi.string().optional(),
  APPLE_CLIENT_ID_2: Joi.string().optional(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().required(),
  DB_USER: Joi.string().required(),
  DB_PASSWORD: Joi.string().optional(),
  DB_NAME: Joi.string().required(),
  DB_TZ: Joi.string().optional(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().required(),
  INVESTMENT_ADVICE_TOOL_URL: Joi.string().required(),
  INTERNAL_SECRET: Joi.string().required(),
  TOKEN_HASH_SECRET: Joi.string().required(),
  FIREBASE_PROJECT_ID: Joi.string().required(),
  FIREBASE_CLIENT_EMAIL: Joi.string().required(),
  FIREBASE_PRIVATE_KEY: Joi.string().required(),
  FIREBASE_DATABASE_URL: Joi.string().required(),
});

export const env = {
  APP: {
    HOST: process.env.APP_HOST || 'localhost',
    PORT: parseInt(process.env.APP_PORT || '3000'),
    NAME: 'tuvi-be',
    ENV: process.env.APP_ENV || 'production',
    APP_URL: process.env.APP_URL,
    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    JWT_EXPIRY: process.env.JWT_EXPIRY || '3600s',
    JWT_REFRESH_EXPIRY: process.env.JWT_REFRESH_EXPIRY || '3d',
    TZ: process.env.TZ || 'Asia/Ho_Chi_Minh',
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
    APPLE_CLIENT_ID: process.env.APPLE_CLIENT_ID || '',
    APPLE_CLIENT_ID_2: process.env.APPLE_CLIENT_ID_2 || '',
    INTERNAL_SECRET: process.env.INTERNAL_SECRET || '',
    TOKEN_HASH_SECRET: process.env.TOKEN_HASH_SECRET || '',
  },
  DATABASE: {
    HOST: process.env.DB_HOST || 'localhost',
    PORT: +(process.env.DB_PORT || 5432),
    USER: process.env.DB_USER || 'admin',
    PASSWORD: process.env.DB_PASSWORD || '',
    DATABASE: process.env.DB_NAME || 'tuvi',
    TZ: process.env.DB_TZ || '+00:00',
  },
  MAIL: {
    HOST: process.env.MAIL_HOST,
    PORT: parseInt(process.env.MAIL_PORT || '587'),
    USER: process.env.MAIL_USER,
    PASS: process.env.MAIL_PASS,
    FROM: process.env.MAIL_FROM,
  },
  REDIS: {
    HOST: process.env.REDIS_HOST,
    PORT: parseInt(process.env.REDIS_PORT || '6379'),
  },
  TOOLS: {
    INVESTMENT_ADVICE_TOOL_URL: process.env.INVESTMENT_ADVICE_TOOL_URL,
  },
  FIREBASE: {
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
  },
};
