import { DataSource } from 'typeorm';
import { ToolMetadata } from '../entities/index.entity';
import {
  InvestmentActionTime,
  InvestmentAsset,
  InvestmentIntendedAction,
  InvestmentNameCode,
  InvestmentRiskExpectation,
  ToolCode,
} from 'src/common/constants/tool.constant';

export class ToolMetadataSeeder {
  constructor(private dataSource: DataSource) {}

  async run() {
    const toolMetadataRepository = this.dataSource.getRepository(ToolMetadata);
    const investmentTool = 'Tool đầu tư';

    const toolMetadata = [
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Bất động sản (Thổ)',
        metaValue: InvestmentAsset.REAL_ESTATE_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Real Estate stocks (Earth element)',
        metaValue: InvestmentAsset.REAL_ESTATE_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Ngân hàng / Chứng khoán (Kim)',
        metaValue: InvestmentAsset.BANKING_SECURITIES_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Banking / Securities stocks (Metal element)',
        metaValue: InvestmentAsset.BANKING_SECURITIES_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Thép / Vật liệu (Kim)',
        metaValue: InvestmentAsset.STEEL_MATERIALS_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Steel / Materials stocks (Metal element)',
        metaValue: InvestmentAsset.STEEL_MATERIALS_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Dầu khí / Vận tải (Thủy)',
        metaValue: InvestmentAsset.OIL_GAS_TRANSPORT_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Oil & Gas / Transportation stocks (Water element)',
        metaValue: InvestmentAsset.OIL_GAS_TRANSPORT_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Bán lẻ / Tiêu dùng (Thủy)',
        metaValue: InvestmentAsset.RETAIL_CONSUMER_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Retail / Consumer stocks (Water element)',
        metaValue: InvestmentAsset.RETAIL_CONSUMER_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Công nghệ / Điện tử (Hỏa)',
        metaValue: InvestmentAsset.TECHNOLOGY_ELECTRONICS_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Technology / Electronics stocks (Fire element)',
        metaValue: InvestmentAsset.TECHNOLOGY_ELECTRONICS_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Điện / Năng lượng (Hỏa)',
        metaValue: InvestmentAsset.ELECTRICITY_ENERGY_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Power / Energy stocks (Fire element)',
        metaValue: InvestmentAsset.ELECTRICITY_ENERGY_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Nông sản / Gỗ (Mộc)',
        metaValue: InvestmentAsset.AGRICULTURE_WOOD_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Agriculture / Timber stocks (Wood element)',
        metaValue: InvestmentAsset.AGRICULTURE_WOOD_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Cổ phiếu Y tế / Dược phẩm (Mộc)',
        metaValue: InvestmentAsset.HEALTH_PHARMA_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Healthcare / Pharmaceuticals stocks (Wood element)',
        metaValue: InvestmentAsset.HEALTH_PHARMA_STOCKS,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Thị trường Chung (VN-Index) (Hỏa)',
        metaValue: InvestmentAsset.VNINDEX_MARKET,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Overall Market (VN-Index) (Fire element)',
        metaValue: InvestmentAsset.VNINDEX_MARKET,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Vàng / Bạc (Kim)',
        metaValue: InvestmentAsset.GOLD_SILVER,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Gold / Silver (Metal element)',
        metaValue: InvestmentAsset.GOLD_SILVER,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Nhóm ngành chứng khoán/tài sản',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Crypto / Bitcoin (Hỏa/Kim)',
        metaValue: InvestmentAsset.CRYPTO_BITCOIN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Securities / Asset sector',
        nameCode: InvestmentNameCode.ASSET,
        metaKey: 'Crypto / Bitcoin (Fire / Metal elements)',
        metaValue: InvestmentAsset.CRYPTO_BITCOIN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Hành động dự định',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'MUA / Đầu tư',
        metaValue: InvestmentIntendedAction.BUY,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'BUY / Invest',
        metaValue: InvestmentIntendedAction.BUY,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Hành động dự định',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'BÁN / Thoát hàng',
        metaValue: InvestmentIntendedAction.SELL,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'SELL / Exit position',
        metaValue: InvestmentIntendedAction.SELL,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Hành động dự định',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'GIỮ VỊ THẾ (Kiểm tra rủi ro)',
        metaValue: InvestmentIntendedAction.HOLD,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action',
        nameCode: InvestmentNameCode.INTENDED_ACTION,
        metaKey: 'HOLD POSITION (Risk check)',
        metaValue: InvestmentIntendedAction.HOLD,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Kỳ vọng rủi ro',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Thận trọng',
        metaValue: InvestmentRiskExpectation.CONSERVATIVE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Risk expectation',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Conservative',
        metaValue: InvestmentRiskExpectation.CONSERVATIVE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Kỳ vọng rủi ro',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Trung bình',
        metaValue: InvestmentRiskExpectation.MODERATE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Risk expectation',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Moderate',
        metaValue: InvestmentRiskExpectation.MODERATE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Kỳ vọng rủi ro',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Mạo hiểm',
        metaValue: InvestmentRiskExpectation.AGGRESSIVE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Risk expectation',
        nameCode: InvestmentNameCode.RISK_EXPECTATION,
        metaKey: 'Aggressive',
        metaValue: InvestmentRiskExpectation.AGGRESSIVE,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Tý (23h–1h)',
        metaValue: InvestmentActionTime.TY,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Zi (23:00–1:00)',
        metaValue: InvestmentActionTime.TY,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Sửu (1h–3h)',
        metaValue: InvestmentActionTime.SUU,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Chou (1:00–3:00)',
        metaValue: InvestmentActionTime.SUU,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Dần (3h–5h)',
        metaValue: InvestmentActionTime.DAN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Yin (03:00–05:00)',
        metaValue: InvestmentActionTime.DAN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Mão (5h–7h)',
        metaValue: InvestmentActionTime.MAO,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Mao (05:00–07:00)',
        metaValue: InvestmentActionTime.MAO,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Thìn (7h–9h)',
        metaValue: InvestmentActionTime.THIN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Chen (07:00–09:00)',
        metaValue: InvestmentActionTime.THIN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Tỵ (9h–11h)',
        metaValue: InvestmentActionTime.TY_,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Si (09:00–11:00)',
        metaValue: InvestmentActionTime.TY_,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Ngọ (11h–13h)',
        metaValue: InvestmentActionTime.NGO,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Wu (11:00–13:00)',
        metaValue: InvestmentActionTime.NGO,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Thân (15h–17h)',
        metaValue: InvestmentActionTime.THAN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Shen (15:00–17:00)',
        metaValue: InvestmentActionTime.THAN,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Dậu (17h–19h)',
        metaValue: InvestmentActionTime.DAU,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'You (17:00–19:00)',
        metaValue: InvestmentActionTime.DAU,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Tuất (19h–21h)',
        metaValue: InvestmentActionTime.TUAT,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Xu (19:00–21:00)',
        metaValue: InvestmentActionTime.TUAT,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 1,
        name: 'Giờ dự định hành động',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Hợi (21h–23h)',
        metaValue: InvestmentActionTime.HOI,
      },
      {
        toolName: investmentTool,
        toolCode: ToolCode.INVESTMENT_TOOL,
        languageId: 2,
        name: 'Intended action time',
        nameCode: InvestmentNameCode.ACTION_TIME,
        metaKey: 'Hai (21:00–23:00)',
        metaValue: InvestmentActionTime.HOI,
      },
    ];

    for (const metadata of toolMetadata) {
      const toolMetadataExist = await toolMetadataRepository.findOne({
        where: metadata,
      });
      if (!toolMetadataExist) {
        const newToolMetadata = toolMetadataRepository.create(metadata);
        await toolMetadataRepository.save(newToolMetadata);
      }
    }
  }
}
