export const SystemConfigCode = {
  ZALO_NUMBER: 'ZALO_NUMBER',
  AI_API_KEY: 'AI_API_KEY',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  AI_PROVIDER_DEFAULT: 'AI_PROVIDER_DEFAULT',
  INVESTMENT_TOOL_BY_HOUR_FILE: 'INVESTMENT_TOOL_BY_HOUR_FILE',
  INVESTMENT_TOOL_BY_DAY_FILE: 'INVESTMENT_TOOL_BY_DAY_FILE',
  INVESTMENT_TOOL_BY_YEAR_FILE: 'INVESTMENT_TOOL_BY_YEAR_FILE',
};
